name: Code Coverage
on:
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests with Coverage
        run: go test -json ./... | jq -s > results.json
      - uses: lindluni/go-test-reporter@main
        with:
          coverage_file: results.json
          coverage_threshold: 90